version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend-transcendence
    restart: always
    # links:
    #   - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   container_name: backend-transcendence
  #   restart: always
  #   links:
  #     - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db-transcendence
    restart: always

    # volumes:
    #   - data:/var/lib/postgresql/data