version: "3.3"

services:
  frontend:
      build: ./frontend
      ports:
        - "3000:3000"
      container_name: frontend-transcendence
      volumes:
        - ./frontend:/usr/src/app/frontend
      restart: always

      #
      #  backend:
      #      build: ./backend/back-nest
      #      ports:
      #        - "3001:3001"
      #      container_name: backend-transcendence
      #      restart: always

  # db:
  #     image: postgres
  #     ports:
  #       - "5432:5432"
  #     container_name: db-transcendence
  #     restart: always

    # volumes:
    #   - data:/var/lib/postgresql/data
