services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: frontend-transcendence
    depends_on:
      - backend
    env_file:
      - .env
    volumes: #remove when development is finished
      - ./frontend/src:/usr/src/app/frontend/src
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${WEBSOCKETS_PORT}:${WEBSOCKETS_PORT}"
    container_name: backend-transcendence
    depends_on:
      - database
    env_file:
      - .env
      - .env.private
    volumes: #remove when development is finished
      - ./backend/src:/usr/src/app/backend/src
    restart: unless-stopped

  database:
    image: postgres:14
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    container_name: ${DATABASE_HOST}
    env_file:
      - .env
      - .env.private
    restart: unless-stopped
